### ISSUE TITLE
Any way to make the script run on remote PI

### ISSUE THREAD

**Issue by jonathanpisarczyk** [acch/nagios-plugins#1]
I have my NagiosXI running as a VM.  I would like to monitor temp on a remote PI.  Can you define myhostaddress as $ARG1$ ?

**Comment by acch** [comment]
No, I haven't implemented any remote execution (via SSH) into the `check_rpi_temp.sh` plugin itself. I'd suggest that you use [NRPE](https://assets.nagios.com/downloads/nagioscore/docs/nrpe/NRPE.pdf) for your use case:

1. On the remote Pi install NRPE: `apt-get install nagios-nrpe-server`

1. Configure NRPE like so: `vi /etc/nagios/nrpe.cfg`
    ```
    ...
    allowed_hosts=<your Nagios server IP>
    ...
    command[check_temp]=/path/to/check_rpi_temp.sh -w 60 -c 70
    ...    
    ```

1. On the Nagios server configure the check like so:
    ```
    ...
    check_command  check_nrpe!check_temp
    ...
    ```

Does that help?

**Comment by jonathanpisarczyk** [comment]
Hello Achim,

Yes that helps!  Thanks.  I got it working!

Regards

Jonathan Pisarczyk
________________________________
