### ISSUE TITLE
check_rpi_temp

### ISSUE THREAD

**Issue by EntropyStorm** [acch/nagios-plugins#2]
I am running NEMSLinux on a Raspberry Pi to monitor several other Raspberry Pis and various network hardware.

Attempting to use check_rpi_temp.sh  to keep an eye on the temperature of the other Pis. I've got it all set up in NRPE, but having an issue with the GPU temperature.

When I run check_rpi_temp.sh on the local Pi, I get the correct information:

`TEMP OK - CPU temperature: 38.628°C - GPU temperature: 38.6°C | cputemp=38.628;60;65;0; gputemp=38.6;60;65;0;`

When I run check_rpi_temp using NRPE from the NEMS server, I get this information:

`TEMP OK - CPU temperature: 39.166°C - GPU temperature: VCHI initialization failed°C | cputemp=39.166;60;65;0; gputemp=VCHI initialization failed;60;65;0;`

**Comment by UnsterblichMedic** [comment]
Having the same issue.  I think it may have something to do with
`printf -v gpuint %.0f "$gpu"`
It's under # Check temperature # and #Read temperature information.  I have tried running the preceding code individually and it works.  However, this bit doesn't seem quite right.  I am not sure though.
It could also be a video group issue with the user (many forums stated this) although I don't know how that would be the issue in this case.  Still looking into it.

**Comment by UnsterblichMedic** [comment]
Good article.  This may be the solution.  I am having other issues so I cannot verify.

https://exchange.nagios.org/directory/Plugins/Hardware/Others/check_rpi_temp-2Epy--2D-Raspberry-Pi-temperature/details

**Comment by EntropyStorm** [comment]
I had issues of my own and am rebuilding my NEMS server. But you might be on to something, since I think the GPU temp does use vcgencmd, whereas the CPU temp is just reading the /sys/class/thermal/thermal_zone0/temp value. Once I get back to that point...

**Comment by EntropyStorm** [comment]
Confirmed that adding the user which the NRPE daemon runs as (default nagios) to the video group solves the issue.

**Comment by acch** [comment]
Awsome :tada: I'm glad you've figured it out.

Do you have a suggestion on how to document this so that others don't run into the same issues? Is this specific to NEMS Linux?

I'm running this script on Arch, nrpe runs with user `nrpe` that's in a private group:
```
# ps -ef | grep nrpe | grep -v grep
nrpe       236     1  0 Nov05 ?        00:00:20 /usr/bin/nrpe -c /etc/nrpe/nrpe.cfg -f
# id nrpe
uid=31(nrpe) gid=31(nrpe) groups=31(nrpe)
```

What's the matter with with `video` group on NEMS?

**Comment by UnsterblichMedic** [comment]
I do not believe it is NEMS specific. The article I linked is for Nagios not necessarily NEMS.

**Comment by EntropyStorm** [comment]
There's nothing wrong with the video group on NEMS. This is actually on the NRPE client, not the NEMS server. The nagios user  and group that gets set up by using the NEMS-specific installation of NRPE as documented on the NEMSLinux site doesn't have permission to use vcgencmd by default.

I've found multiple solutions to the issue by Googling it, but the easiest way is to just add the nagios user to the video group (on each NRPE client, not on the NEMS server).

**Comment by EntropyStorm** [comment]
All I did was enter the following command in the SSH shell of each NRPE client (I have 2 currently), then reboot. Probably could have just restarted the NRPE daemon, but it's been a while since I rebooted the SBCs anyway.

`sudo usermod -G video nagios`
